name: Aggregate on Push

on:
  push:
    branches: [ master ]

jobs:
  aggregate-references:
    name: Aggregate References
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Python Script
        run: python aggregate.py
        env:
          TZ: 'Asia/Tokyo'
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Aggregated references.md
